#!/system/bin/sh

(
if grep crpalmer /proc/version > /dev/null
then
   echo "** crpalmer's boot configuration:"
   stop mpdecision
   stop thermald
   for script in /system/etc/crpalmer/*
   do
	$script
   done
else
   echo "!! crpalmer's boot configuration not running, this isn't my kernel !!"
fi
)2>&1 | tee /sdcard/crpalmer.log
